comment:
  layout: header, changes, diff, sunburst
coverage:
  precision: 0
  round: down
  range: "30...80"
  status:
    patch:
      default:
        target: '30'
    project:
      default:
        target: auto
